---
title: "IODS course project"
author: 'Andrew H House'
output:
    html_document:
      theme: cosmo
      toc: yes
     # number_sections: true  ## if you want number sections at each table header
      toc_depth: 2
      fig_caption: true
      fig_width: 6
      fig_height: 4
---

***

# Introduction to Open Data Science - Course Project


```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```
  
***
  
 
```{r child = "chapter2.Rmd"}
# This will include Chapter 2 (that is updated in its own file) in the document.Updated
```

***


```{r child = "chapter3.Rmd"}
# This will include Chapter 3 (that is updated in its own file) in the document.Updated!!
```

***

```{r child = "chapter4.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.Updated!!
```

***

```{r child = "chapter5.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.Updated!!
```

***

```{r child = "chapter6.Rmd"}
# This will include Chapter 6 (that is updated in its own file) in the document.Updated!!

```



